### ISSUE TITLE
Also Hue Dimmer problem

### ISSUE THREAD

**Issue by GrimmJok3r** [sebbebebbe/com.philips.hue.zigbee#164]
Hi,

I have the same shit with my dimmers as off yesterday morning after a Homey PowerCycle.
Switches worked for years without any issue but they just stopped.
I see you have said multiple times to other users that this is a known issue but it’s still not fixed.
If somebody has a solution so half of my lights will work again that would be nice during the holiday season.

What have I Tried
Rebooted Homey
Power Cycled Homey
Made a Test flow with a simple and easy to check "Then" statement
Removed and added a Dimmer Switch ( Adding without issue )
Removed and Reinstalled the App
Disabled the App rebooted Homey started it again.
Removed the App rebooted Homey and installed it again.
Added Dimmer Switches to the Hue Bridge, Updated them to the latest Firmware, Added it to Homey again.

All without success.

I have generated a diagnostics rapport
ca144983-145b-439e-b9c2-2bcabb21d7f5

Have also contacted Athom support about it.

Last thing I can do for now is add the Dimmers back to the Hue Bridge and Let Homey read the status from the bridge and them let it start my Light Flow's but this is far from Ideal with the 5Second Polling shit.

Hope you have a work arround till a viable solution is found

Thx in advance and have a nice Christmas

**Comment by madmax75** [comment]
Same here

**Comment by GrimmJok3r** [comment]
Just got an answer from Athom stating what we already know.

Here is the message I received ( in Dutch )

Hi Thijs,

Bedankt dat je contact met ons hebt opgenomen, mijn excuses voor de vertraagde reactie.

Helaas heb ik niet zo heel veel aan je app specifieke log omdat ik hier geen toegang toe heb, deze toegang ligt alleen bij de ontwikkelaar van de Hue ZigBee app ;-)

Ik vermoed dat je probleem veroorzaakt wordt door onze implementatie van ZigBee in Homey, wat waarschijnlijk ook is wat de developer je verteld heeft.

Hier zitten een aantal bugs in waardoor apparaten soms niet aangestuurd kunnen worden, of de signalen van apparaten niet goed verwerkt worden.

We werken hard aan een update voor onze ZigBee implementatie zodat deze problemen allemaal verholpen worden. Helaas is deze code extreem gecompliceerd, waardoor het nog enige tijd kan duren voordat we dit kunnen uitbrengen.

Helaas betekend dit dat ik mbt dit probleem verder niks voor je kan betekenen totdat deze update uitgerold is.

Mijn excuses voor het ongemak.

Met vriendelijke groet,
Best Regards,

Boaz

The Athom support team.

**Comment by pardeike** [comment]
+1 on this. I have a pretty complex setup and everything works well - except that I loose my 4-button-philips-hue switches all the time. Previously, I could restart the app after a power cycle of the Homey itself but this has stopped as a workaround too.

As a developer myself, I have a gut feeling that it's the app and not the homey's code that causes this. If I had time I would work this project and try to fix it myself.

**Comment by GrimmJok3r** [comment]
Sinds 2 days it seems my problems have been solved.

I have a lot of xiaomi motion sensors that have issues as well homey won’t detect te motion and they won’t start the flows

Because of that i start reading the community again and found a post about zigbee and that WiFi 2,4ghz ch11 is around the same frequency.
Because of this and overlapping of channels is disabled the use off channels 9 to 13 on my accesspoints
As if by magic sinds then my hue dimmers work again

My theory is that one of my AP’s was using ch11 and homey was connected to it an so was in the way of the ZigBee stuff
My Xiaomi stuff also seem to work properly now 

I want to test it by enabling only ch11 to know for sure but my wife and kids are so happy the work again

Hope this work around will help some of you too

**Comment by rzarajczyk** [comment]
I have the same issue - three Dimmer Switches stopped working at the same time. Unfortunately changing router channel didn't help - I still can't control my lights.

**Comment by GrimmJok3r** [comment]
Damn
Homey updated last night and the shit stopped working again

Getting real sick of this shit

**Comment by PeterThornton4Ing** [comment]
Same problem here. All my Hue dimmer switches is dead. My wife is not happy, to say it midly

**Comment by pardeike** [comment]
After a full network reset I got my two hue dimmer switches working. Took two days and they were gone. At which point it’s impossible to pair them again in any way.

**Comment by PeterThornton4Ing** [comment]
Well. Resetting the network is out of the question. I'm not gonna spend that much time setting everything up again.

**Comment by martepartje** [comment]
Mine works again!!!
After the homey update to 4.1.0 the Hue dimmer switch is working like a charm....now 5 days ago.

**Comment by JohanBendz** [comment]
If this is still a problem with the latest test version (soon stable) please start a new issue.
