### ISSUE TITLE
No pairing with Hue Being pendant

### ISSUE THREAD

**Issue by KJE01** [sebbebebbe/com.philips.hue.zigbee#334]
Hi,

My Hue Being pendant won’t pair with my Homey. I have no Hue bridge and there is a Fibaro switch between the lamp and the light switch. The app tells me to either turn on the light or reset the lamp with the remote. Both methods don’t work. The Homey was under the lamp, so very close.

Hue refers to Athom and Athom refers to you. Any idea what to do?

Thank you!

**Comment by JohanBendz** [comment]
Hi @KJE01, hope this was solved. If not please get back to me.

**Comment by KJE01** [comment]
> Hi @KJE01, hope this was solved. If not please get back to me.

**Comment by KJE01** [comment]
Hi @JohanBendz, unfortunately this was not solved yet. Hopefully you have an idea how to solve it.

**Comment by JohanBendz** [comment]
Hi again.
OK, try adding the device as a generic Zigbee device. If this does not work the issue is not in this app but in Homey Zigbee.
If you are able to add the device as a generic device please interview it using developer tools: https://tools.developer.homey.app/tools/zigbee

If you are unable to add it at all I suggest checking in developer tools that you have enough routers in place, Homey can only talk directly with aprox 15 units and any other unit is then routed via those first units. If your first 15+ units are battery operated they will not route.
